
name: Version Bump & Release

on:
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_MCP342X_TOKEN }}
          name: CodeCov-MCP342x # optional
          files: ./build/artifacts/gcov/GcovCoverageCobertura.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)